### ISSUE TITLE
Enabling in a subscript doesn't appear to work

### ISSUE THREAD

**Issue by ThomasSeidler** [jbante/FileMaker-Techniques#3]
My reading is that you are meant to be able to disable triggers in a parent script and then enable triggers in a subscript. This does not work in my testing, but possibly I have misunderstood your intent? Thanks for the great work btw.

**Comment by jbante** [comment]
That is not the intent. The intent is for a triggers-off setting from a parent script to remain in effect, even after a child script turns them off and is no longer needs them off for it's own purposes. The child script is presumably ignorant of the parent script's reasons for triggers to be off, and for the parent script's triggers-off decision to take precedence over a child script's triggers-on decision. If triggers need to be enabled during a child script, the highest-level parent script in the stack should re-enable triggers before calling a child script to delegate full authority over that decision to any child scripts.

**Comment by ThomasSeidler** [comment]
Thanks for the swift response. I understand the intent clearly now. There are some instances where that might get a little complex - but perhaps only for me! I use a custom dialog system (cos FileMaker's offering is insufficient) that depends on triggers being active. Thus, when deep down in batch processing scripts (that wanted script triggers off) I decided to throw a dialog for key user interaction, I had a mild problem! And logically the dialogue script would always want to override TriggersDisable, so it seemed more logical to make an override possible.

My solution atm is thus:

### NEW CF
**TriggersForceEnable**
```
// 'force' enable in local script only, disabled by TriggersDisable
TriggersEnable & 
If ( TriggersAreDisabled ; Let ( $~triggers_forceEnableKey = Get( UUID ) ; "" ) )
```
### Add'l Changes Rq'd
**TriggersAreDisabled**: `$$~TRIGGERS_DISABLE and not Length ( $~triggers_forceEnableKey )`
**TriggersDisable** & **TriggersReset**: `$~triggers_forceEnableKey = "" ;`
**TriggersAreActive**: `not ( TriggersAreDisabled )`

Just an idea while I try to maintain the neatness and logical clarity of your implementation without over-complicating a simple and momentary effective override to re-activate triggers.

This is certainly not a complaint, but an offering in gratitude for your sublime work (on a number of counts)! :pensive: Albeit misguided perhaps! ;)

Many thanks once again for your work, Tom

**Comment by jbante** [comment]
Another possibility to consider might be to re-arrange the scripts implementing your batch process so that the points where you might want any kind of user input pass control back to the parent script. Any points calling for user input are already noteworthy enough break points to bother the user for input. There's a good chance they're also noteworthy enough for control to find its way back to the top script of the process.

**Comment by ThomasSeidler** [comment]
yeah,

you make a sound point.

Perhaps bad constructs, but i tend to write my large routines so as to keep logic all in one place as much as possible, and avoid multiplication of scripts – thus:

++++++++++++++++++
OSM: Monthly Routine [ action ; some variables etc ]
++++++++++++++++++

TriggersDisable [cos i want off for all these scripts]


if ( $action = "main" )
	perform script [ self ; $action = "pre-run checks" ]
	perform script [ self ; $action = "generate charts" ]
	perform script [ self ; $action = "get stock data" ]
	perform script [ self ; $action = "send email" ]
else if ( $action = "pre-run checks" )
	do stuff
else if ( $action = "generate charts" )
	if ( Length( $$_OSM_images ) )
		perform script [ MyDialog ; "Do you want to use existing images, or generate new ones?" ]
	end if
	use existing images or not
else if ( $action = "get stock data" )
	do stuff
else if ( $action = "send email" )
	perform script [ MyDialog ; "Do you want to send test email or final?" ]
	send email
end if


TriggersEnable
++++++++++++++

so the override within MyDialog is useful…


T
